Repository Review-zip/ReviewZip-BE, pull requests merged in 2024-02, with the labels that each got.

#134 [Refactor] 생성 시간 포맷 수정
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
Labels: :recycle: 리팩터링, 로그

#133 [Feat] 게시글 스크랩하기/취소하기
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/scrab/Scrabs.java
  src/main/java/com/example/ReviewZIP/domain/scrab/ScrabsRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
Labels: :sparkles: 기능, 로그

#138 [Feat] main merge
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/scrab/Scrabs.java
  src/main/java/com/example/ReviewZIP/domain/scrab/ScrabsRepository.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchType.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
Labels: :sparkles: 기능, 로그

#143 [Feat] main merge
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsConverter.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
  src/main/java/com/example/ReviewZIP/domain/oauth/dto/Response/OauthResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/oauth/dto/request/OauthRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistories.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
Labels: :recycle: 리팩터링, :zap: 수정

#141 [Feat] 해시태그 이름으로 해시태그 검색하기
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
Labels: :sparkles: 기능, 이피

#151 [Feat] 일부 함수 반환값 수정
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
Labels: :recycle: 리팩터링, 로그

#154 [Feat] 유저 및 해시태그 검색 기록 저장 및 삭제
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistories.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesController.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesService.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/HistoryHandler.java
Labels: :sparkles: 기능, 로그

#156 [Feat] 검색기록 가져오기 API
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/SearchHandler.java
Labels: :sparkles: 기능, 로그

#159 [Dev] main merge
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistories.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesController.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesService.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/HistoryHandler.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/SearchHandler.java
Labels: :sparkles: 기능, 로그

#164 [Refactor] dto 및 검색기록 최신순 정렬
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
Labels: :recycle: 리팩터링, 로그

#160 [Feat] 랜덤으로 하나의 게시물 가져오기
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능, 댕

#166 [Dev] main merge
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :recycle: 리팩터링, 댕

#173 [Feat] 로컬 로그인/회원가입 구현
  build.gradle
  src/main/java/com/example/ReviewZIP/domain/token/RefreshToken.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenRepository.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/LoginRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/SignUpRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/SignUpResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/TokenDto.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtProvider.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtRequestFilter.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtSecurityConfig.java
  src/main/java/com/example/ReviewZIP/global/resolver/ArgumentResolver.java
  src/main/java/com/example/ReviewZIP/global/resolver/WebConfig.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/security/CorsConfig.java
  src/main/java/com/example/ReviewZIP/global/security/SecurityUtil.java
  src/main/java/com/example/ReviewZIP/global/security/UserDetailsImpl.java
  src/main/java/com/example/ReviewZIP/global/security/UserDetailsServiceImpl.java
  src/main/java/com/example/ReviewZIP/global/security/WebSecurityConfig.java
Labels: :sparkles: 기능, 시온

#175 [Feat] 로컬 로그인, 회원가입 구현
  build.gradle
  src/main/java/com/example/ReviewZIP/domain/token/RefreshToken.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenRepository.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/LoginRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/SignUpRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/SignUpResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/TokenDto.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtProvider.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtRequestFilter.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtSecurityConfig.java
  src/main/java/com/example/ReviewZIP/global/resolver/ArgumentResolver.java
  src/main/java/com/example/ReviewZIP/global/resolver/WebConfig.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/security/CorsConfig.java
  src/main/java/com/example/ReviewZIP/global/security/SecurityUtil.java
  src/main/java/com/example/ReviewZIP/global/security/UserDetailsImpl.java
  src/main/java/com/example/ReviewZIP/global/security/UserDetailsServiceImpl.java
  src/main/java/com/example/ReviewZIP/global/security/WebSecurityConfig.java
Labels: :sparkles: 기능, 시온

#174 [Feat] 내 정보 가져오기 API
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능, 로그

#181 [Refactor] 반환값 수정 및 dto 및 함수 수정 re
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
  src/main/java/com/example/ReviewZIP/domain/image/ImageConverter.java
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/UploadImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/jwt/JwtProperties.java
  src/main/java/com/example/ReviewZIP/domain/jwt/TokenProvider.java
  src/main/java/com/example/ReviewZIP/domain/oauth/KakaoController.java
  src/main/java/com/example/ReviewZIP/domain/oauth/OauthService.java
  src/main/java/com/example/ReviewZIP/domain/oauth/dto/Response/OauthResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/oauth/dto/request/OauthRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
Labels: :recycle: 리팩터링, 로그

#183 [Fix] CorsConfig 관련 코드 수정
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
  src/main/java/com/example/ReviewZIP/global/security/CorsConfig.java
  src/main/java/com/example/ReviewZIP/global/security/WebSecurityConfig.java
Labels: :zap: 수정, 시온

#185 [Refactor] 해시태그로 해시태그 검색 수정
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
Labels: :zap: 수정, 로그

#188 [Feat] 마이페이지 프로필 이미지 및 닉네임 수정
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/request/UserRequestDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능, 시온

#190 [Dev] main merge
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/request/UserRequestDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :wrench: 설정, 로그

#194 [Refactor] 해시태그 정보 게시글 갯수 추가
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
Labels: :recycle: 리팩터링, 로그

#195 [Dev] main merge
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsConverter.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
Labels: :wrench: 설정, 로그

#198 [Fix] 게시글 생성 오류 수정
  src/main/java/com/example/ReviewZIP/domain/image/ImageConverter.java
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/UploadImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
Labels: :zap: 수정, 로그

#199 [Dev] main merge
  src/main/java/com/example/ReviewZIP/domain/image/ImageConverter.java
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/UploadImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
Labels: :zap: 수정, 로그

#191 [Feat] 로그인 성공한 유저 정보 받아오기 기능 구현
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/request/LoginRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/request/SignUpRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/response/SignUpResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/token/dto/response/TokenDto.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/global/jwt/JwtProvider.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/UsersHandler.java
Labels: :sparkles: 기능, 시온

#215 [Feat] 토큰 이용 아이디 반환
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/global/security/UserDetailsServiceImpl.java
Labels: :sparkles: 기능, 로그

#217 [Refactor] 토큰 인증기반 기능 수정
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsService.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesController.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesRepository.java
  src/main/java/com/example/ReviewZIP/domain/searchHistory/SearchHistoriesService.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
Labels: :recycle: 리팩터링, 로그

#228 [Fix] 스프링 시큐리티 관련 에러 수정
  src/main/java/com/example/ReviewZIP/global/jwt/JwtProvider.java
  src/main/java/com/example/ReviewZIP/global/logback/LoggingFilter.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/resources/logback.xml
Labels: :zap: 수정, 시온

#230 [Refactor] 게시글 생성 API 수정
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
Labels: :recycle: 리팩터링, 로그

#235 [Feat] SMS 인증번호 인증 후 비밀번호 변경 API 구현
  build.gradle
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/global/config/RedisConfig.java
  src/main/java/com/example/ReviewZIP/global/config/SmsCertificationConfig.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/SmsHandler.java
  src/main/java/com/example/ReviewZIP/global/sms/SmsController.java
  src/main/java/com/example/ReviewZIP/global/sms/SmsRepository.java
  src/main/java/com/example/ReviewZIP/global/sms/SmsService.java
  src/main/java/com/example/ReviewZIP/global/sms/dto/request/SmsDto.java
Labels: :sparkles: 기능, 시온

#240 [Fix] 프로필 이미지, 닉네임 수정 API 수정
  src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/request/UserRequestDto.java
Labels: :zap: 수정, 시온

#246 [Refactor] 게시글 가져오기 API
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/store/StoresRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/StoreHandler.java
Labels: :recycle: 리팩터링, 로그

#248 [Refactor] 액세스 토큰 값 수정
  src/main/java/com/example/ReviewZIP/global/jwt/JwtProvider.java
Labels: :recycle: 리팩터링, 시온

#252 [Refactor] domain dto 리팩터링
  src/main/java/com/example/ReviewZIP/domain/image/ImageConverter.java
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
Labels: :recycle: 리팩터링, 댕

#253 [Dev] main merge
  src/main/java/com/example/ReviewZIP/domain/image/ImageConverter.java
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/dto/response/PostHashtagResponseDto.java
Labels: :recycle: 리팩터링, 댕
