Repository Review-zip/ReviewZip-BE, pull requests merged in 2024-01, with the labels that each got.

#70 [CI] Github Actions 파일 생성
  .github/workflows/dev-deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/Posts.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesRepository.java
  src/main/java/com/example/ReviewZIP/domain/scrab/ScrabsRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersConverter.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/request/FollowRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/ReviewZIP/global/entity/BaseEntity.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/FollowsHandler.java
Labels: :green_heart: CI, 로그

#73 [CI] github action
  .github/workflows/dev-deploy.yml
Labels: :green_heart: CI, 로그

#74 [ci] github action
  .github/workflows/dev-deploy.yml
Labels: :green_heart: CI, 로그

#75 [ci] github actions
  .github/workflows/dev-deploy.yml
Labels: :zap: 수정, :green_heart: CI, 로그

#76 [ci] github action 코드 수정
  .github/workflows/dev-deploy.yml
Labels: :zap: 수정, :green_heart: CI, 로그

#77 [ci] github actions 코드 수정
  .github/workflows/dev-deploy.yml
Labels: :green_heart: CI

#78 [ci ]: github action 수정
  .github/workflows/dev-deploy.yml
Labels: :zap: 수정, :green_heart: CI, 로그

#79 [ci] github actions 수정
  .github/workflows/dev-deploy.yml
Labels: :zap: 수정, :green_heart: CI, 로그

#88 [CI ] 자동배포 파일 생성
  .github/workflows/dev-deploy.yml
Labels: :recycle: 리팩터링, :green_heart: CI, 로그

#89 [CI] 자동 배포 코드 추가
  .github/workflows/dev-deploy.yml
Labels: :recycle: 리팩터링, :green_heart: CI, 로그

#56 [Feat] 게시글 생성
  build.gradle
  src/main/java/com/example/ReviewZIP/domain/post/Posts.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/global/config/RedisConfig.java
  src/main/java/com/example/ReviewZIP/global/redis/RedisService.java
Labels: :sparkles: 기능, 댕

#85 [Feat] 랜덤으로 게시글 3개 가져오기
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/request/PostRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesRepository.java
  src/main/java/com/example/ReviewZIP/domain/scrab/ScrabsRepository.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능, 댕

#99 [Docs] swagger 응답 작성
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :memo: 문서, 로그

#102 [Refactor] 불필요한 예외처리 삭제
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/request/FollowRequestDto.java
Labels: :zap: 수정, 로그

#103 [Refactor] 불필요한 예외처리 삭제
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsConverter.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/request/FollowRequestDto.java
Labels: :recycle: 리팩터링, 로그

#24 [Feat] 유저아이디로 유저 팔로우
  src/main/java/com/example/ReviewZIP/domain/follow/Follows.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsConverter.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepositoy.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsService.java
  src/main/java/com/example/ReviewZIP/domain/follow/dto/response/FollowResponseDto.java
  src/main/java/com/example/ReviewZIP/domain/post/Posts.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/scrab/Scrabs.java
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능, 로그

#27 [Feat] 유저아이디로 유저 언팔로우
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsController.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsConverter.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepository.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsRepositoy.java
  src/main/java/com/example/ReviewZIP/domain/follow/FollowsService.java
  src/main/java/com/example/ReviewZIP/domain/follow/dto/response/FollowResponseDto.java
Labels: :sparkles: 기능, 로그

#26 [Feat] 유저 삭제
  src/main/java/com/example/ReviewZIP/domain/user/Users.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
  src/main/java/com/example/ReviewZIP/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능, 로그

#44 [Feat] 포스트에 공감 해제하기
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesController.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesConverter.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesService.java
  src/main/java/com/example/ReviewZIP/domain/postLike/dto/request/PostLikesRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/postLike/dto/response/PostLikesResponseDTO.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/PostLikesHandler.java
Labels: :sparkles: 기능, 이피

#106 [docs] 카카오 로그인 swagger 추가
  src/main/java/com/example/ReviewZIP/domain/oauth/KakaoController.java
  src/main/java/com/example/ReviewZIP/domain/oauth/OauthService.java
  src/main/java/com/example/ReviewZIP/domain/oauth/dto/request/OauthRequestDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/GeneralHandler.java
Labels: :memo: 문서, 로그

#107 [Docs] 소셜로그인 swagger 추가
  src/main/java/com/example/ReviewZIP/domain/oauth/KakaoController.java
  src/main/java/com/example/ReviewZIP/domain/oauth/OauthService.java
  src/main/java/com/example/ReviewZIP/domain/oauth/dto/request/OauthRequestDto.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikes.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesController.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesConverter.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesRepository.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesService.java
  src/main/java/com/example/ReviewZIP/domain/postLike/dto/request/PostLikesRequestDto.java
  src/main/java/com/example/ReviewZIP/global/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/GeneralHandler.java
  src/main/java/com/example/ReviewZIP/global/response/exception/handler/PostLikesHandler.java
Labels: :memo: 문서, 로그

#53 [Feat] 나의 게시글들 가져오기
  src/main/java/com/example/ReviewZIP/domain/post/PostsRepository.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
Labels: :sparkles: 기능, 로그

#62 [Feat] 게시글 삭제하기
  src/main/java/com/example/ReviewZIP/domain/post/Posts.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
Labels: :sparkles: 기능, 로그

#113 [Refactor] 트랜잭션 수정
  src/main/java/com/example/ReviewZIP/domain/image/ImagesController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsController.java
  src/main/java/com/example/ReviewZIP/domain/post/PostsService.java
  src/main/java/com/example/ReviewZIP/domain/postHashtag/PostHashtagsService.java
  src/main/java/com/example/ReviewZIP/domain/postLike/PostLikesService.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
Labels: :recycle: 리팩터링, :memo: 문서, 댕

#115 [Feat] 나의 팔로워 목록 가져오기
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
Labels: :sparkles: 기능, 로그

#116 [Feat] 내가 스크랩한 게시글 목록 가져오기
  src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
  src/main/java/com/example/ReviewZIP/domain/user/UsersService.java
Labels: :sparkles: 기능, 로그
